[package]
name = "tachi-params"
version = "1.9.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
memcore = { path = "../memcore" }
chrono = { workspace = true }
rmcp = { version = "1.2", features = ["schemars"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
