use serde_json::{json, Value};

pub const SIMULATED_SKILL_OUTPUT_MARKER: &str =
    "[SIMULATED — LLM-generated skill output. No commands, files, or tests were executed.]";

pub const SIMULATED_SKILL_OUTPUT_WARNING: &str = "This output was generated by a language model from the skill's prompt template. It did not execute commands or read the repository. Do not treat concrete values (commit hashes, line numbers, test results, file paths) as verified facts.";
const DOCUMENT_SKILL_INSTRUCTION: &str = "This is a workflow document. Follow its steps yourself using your own tools; do not treat it as executed output.";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkillExecutionMode {
    LlmGenerated,
    MockResponse,
    Document,
}

impl SkillExecutionMode {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::LlmGenerated => "llm_generated",
            Self::MockResponse => "mock_response",
            Self::Document => "document",
        }
    }

    pub fn is_simulated(self) -> bool {
        matches!(self, Self::LlmGenerated | Self::MockResponse)
    }
}

#[derive(Debug, Clone)]
pub struct SkillExecution {
    pub output: String,
    pub execution: SkillExecutionMode,
}

pub fn build_skill_execution_envelope(
    skill_id: &str,
    execution: SkillExecution,
    tool_name: Option<&str>,
) -> Value {
    let simulated = execution.execution.is_simulated();
    let output = if simulated {
        format!("{}\n\n{}", SIMULATED_SKILL_OUTPUT_MARKER, execution.output)
    } else {
        execution.output
    };

    let mut envelope = json!({
        "status": "completed",
        "action": "run",
        "skill_id": skill_id,
        "execution": execution.execution.as_str(),
        "simulated": simulated,
        "output": output,
    });
    if let Some(tool_name) = tool_name {
        envelope["tool_name"] = json!(tool_name);
    }
    if simulated {
        envelope["warning"] = json!(SIMULATED_SKILL_OUTPUT_WARNING);
    }
    if execution.execution == SkillExecutionMode::Document {
        envelope["instruction"] = json!(DOCUMENT_SKILL_INSTRUCTION);
    }
    envelope
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simulated_skill_envelope_warns_and_marks_output() {
        let envelope = build_skill_execution_envelope(
            "skill:test",
            SkillExecution {
                output: "hello".to_string(),
                execution: SkillExecutionMode::MockResponse,
            },
            Some("tachi_skill_test"),
        );

        assert_eq!(envelope["simulated"], true);
        assert_eq!(envelope["tool_name"], "tachi_skill_test");
        assert!(envelope["output"]
            .as_str()
            .expect("output")
            .starts_with(SIMULATED_SKILL_OUTPUT_MARKER));
        assert_eq!(envelope["warning"], SIMULATED_SKILL_OUTPUT_WARNING);
    }

    #[test]
    fn document_skill_envelope_instructs_without_simulation_warning() {
        let envelope = build_skill_execution_envelope(
            "skill:doc",
            SkillExecution {
                output: "read this".to_string(),
                execution: SkillExecutionMode::Document,
            },
            None,
        );

        assert_eq!(envelope["simulated"], false);
        assert!(envelope.get("warning").is_none());
        assert_eq!(
            envelope["instruction"],
            "This is a workflow document. Follow its steps yourself using your own tools; do not treat it as executed output."
        );
    }
}
