/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Check if text is noise. */
export declare function isNoise(text: string): boolean
/** Check if query should skip retrieval. */
export declare function shouldSkip(query: string): boolean
/** Thread-safe wrapper around the Rust MemoryStore. */
export declare class JsMemoryStore {
  /** Open a store at `db_path`. Creates the file & schema if needed. */
  constructor(dbPath: string)
  /** Upsert a memory entry. `entry_json` is a JSON string of MemoryEntry. */
  upsert(entryJson: string): void
  /**
   * Hybrid search. Returns a JSON string of SearchResult[].
   *     "path_prefix": "/some/path"
   * }
   */
  search(query: string, optionsJson?: string | undefined | null): string
  /** Delete a memory by ID. */
  delete(id: string): boolean
  /** Get aggregate stats. Returns JSON string. */
  stats(includeArchived?: boolean | undefined | null): string
  /** Fetch a single memory by ID. Returns JSON string or null. */
  get(id: string): string | null
  /** Get most recent entries up to `limit`. Returns JSON string of MemoryEntry[]. */
  getAll(limit?: number | undefined | null): string
  /** Returns true if the sqlite-vec extension was loaded successfully. */
  get vecAvailable(): boolean
}
