#!/usr/bin/env bash
# Generate the public `memcore` mirror from this monorepo (owner-ratified plan B,
# 2026-08-10): Tachi stays the single source; the mirror is a generated artifact
# (#873 pattern — single source + generated embed). Downstream consumers
# (zeroclaw, Hypermem) git-dep the mirror instead of this private repo.
#
# The mirror contains exactly:
#   memcore/           <- crates/memcore        (verbatim)
#   portable-kernel/   <- crates/portable-kernel (verbatim)
#   Cargo.toml         <- generated workspace root (deps subset of ours)
#   LICENSE            <- repo root LICENSE (AGPL-3.0)
#   README.md          <- generated (mirror notice + consumer contract)
#   MIRROR_SOURCE      <- source commit sha, for provenance / parity checks
#
# Usage: scripts/publish_memcore_mirror.sh <output-dir> [source-ref]
# Idempotent; output dir is wiped and rebuilt. Does NOT push — pushing is the
# caller's job (CI workflow or a human).
set -euo pipefail

OUT=${1:?usage: publish_memcore_mirror.sh <output-dir> [source-ref]}
REF=${2:-HEAD}
ROOT=$(git rev-parse --show-toplevel)
SHA=$(git -C "$ROOT" rev-parse "$REF")

rm -rf "$OUT"
mkdir -p "$OUT"

# Crates: verbatim export from the given ref (not the dirty worktree).
for crate in memcore portable-kernel; do
  mkdir -p "$OUT/$crate"
  git -C "$ROOT" archive "$SHA" "crates/$crate" | tar -x -C "$OUT" --strip-components=1 -f -
done

# LICENSE: verbatim.
git -C "$ROOT" show "$SHA:LICENSE" > "$OUT/LICENSE"

# Workspace root: members + ONLY the workspace deps the two crates use.
# Extracted from the source root Cargo.toml at the same ref so specs never drift.
DEPS=$(git -C "$ROOT" show "$SHA:Cargo.toml" \
  | sed -n '/^\[workspace.dependencies\]/,/^\[/p' \
  | grep -E '^(rusqlite|serde|serde_json|sha2|uuid|thiserror|tracing|chrono|regex|sqlite-vec)[ =]')

cat > "$OUT/Cargo.toml" <<TOML
# GENERATED by scripts/publish_memcore_mirror.sh in the tachi monorepo.
# Do not edit here — changes land in tachi and are mirrored on merge.
[workspace]
members = ["memcore", "portable-kernel"]
resolver = "2"

[workspace.dependencies]
$DEPS
TOML

cat > "$OUT/README.md" <<'MD'
# memcore — portable memory kernel (read-only mirror)

Store, schema, hybrid FTS+vector search/scorer, graph, events, durable outbox
with idempotent reconciliation. AGPL-3.0-only.

**This repository is a generated mirror.** The source of truth is a private
monorepo; every merge there regenerates this repo. Issues and pull requests
opened here are not watched and will be overwritten.

## Consuming

Depend on the portable build shape (the supported external surface):

```toml
memcore = { git = "https://github.com/kckylechen1/memcore", default-features = false }
```

or equivalently on the `portable-kernel` facade crate in this workspace.
`default-features = false` omits the product/admin surfaces (vault, hub,
foundry job queue, pack). A database created by a portable build carries only
the portable kernel schema; it can open a full-product database, never the
reverse.

`MIRROR_SOURCE` records the source commit each publish was generated from.
MD

echo "$SHA" > "$OUT/MIRROR_SOURCE"

echo "mirror generated at $OUT from $SHA"
