use super::*;

const MOCK_SKILL_ID: &str = "skill:mock-run-envelope";

fn tachi_skill_run_params(skill_id: &str, args: Value) -> TachiSkillParams {
    TachiSkillParams {
        action: "run".to_string(),
        query: None,
        cap_type: None,
        enabled_only: None,
        limit: None,
        skill_id: Some(skill_id.to_string()),
        args: Some(args),
        profile: None,
        host: None,
        skill_limit: None,
        capability_limit: None,
        pack_limit: None,
        include_section: None,
    }
}

fn register_mock_skill_params() -> HubRegisterParams {
    HubRegisterParams {
        id: MOCK_SKILL_ID.to_string(),
        cap_type: "skill".to_string(),
        name: "mock-run-envelope".to_string(),
        description: "safe mock skill".to_string(),
        definition: json!({
            "prompt": "Return a safe mocked result for {{input}}.",
            "mock_response": "mocked command output",
            "policy": {"visibility": "listed"},
            "inputSchema": {
                "type": "object",
                "properties": {
                    "input": {"type": "string"}
                }
            }
        })
        .to_string(),
        version: 1,
        scope: "global".to_string(),
    }
}

fn first_text_payload(result: &rmcp::model::CallToolResult) -> Value {
    let text = result
        .content
        .iter()
        .find_map(|content| match &content.raw {
            rmcp::model::RawContent::Text(text) => Some(text.text.as_str()),
            _ => None,
        })
        .expect("text tool result");
    serde_json::from_str(text)
        .unwrap_or_else(|err| panic!("tool result json: {err}; text={text:?}"))
}

fn assert_mock_simulation_envelope(value: &Value) {
    assert_eq!(value["status"], json!("completed"));
    assert_eq!(value["action"], json!("run"));
    assert_eq!(value["skill_id"], json!(MOCK_SKILL_ID));
    assert_eq!(value["execution"], json!("mock_response"));
    assert_eq!(value["simulated"], json!(true));
    assert_eq!(
        value["warning"],
        json!("This output was generated by a language model from the skill's prompt template. It did not execute commands or read the repository. Do not treat concrete values (commit hashes, line numbers, test results, file paths) as verified facts.")
    );
    assert!(value["output"]
        .as_str()
        .expect("output text")
        .starts_with(crate::hub_ops::SIMULATED_SKILL_OUTPUT_MARKER));
}

#[tokio::test]
async fn tachi_skill_run_mock_response_returns_simulation_envelope() {
    let server = make_server();
    let register_response = server
        .hub_register(Parameters(register_mock_skill_params()))
        .await
        .expect("hub_register mock skill");
    let registered: Value = serde_json::from_str(&register_response).expect("register response");
    assert_eq!(
        registered["tool_name"],
        json!("tachi_skill_mock_run_envelope")
    );

    let response = server
        .tachi_skill(Parameters(tachi_skill_run_params(
            MOCK_SKILL_ID,
            json!({"input": "fixture"}),
        )))
        .await
        .expect("tachi_skill run should succeed");
    let envelope: Value = serde_json::from_str(&response).expect("run response json");

    assert_mock_simulation_envelope(&envelope);
}

#[tokio::test]
async fn direct_skill_tool_mock_response_returns_same_simulation_envelope_fields() {
    let server = make_server();
    server
        .hub_register(Parameters(register_mock_skill_params()))
        .await
        .expect("hub_register mock skill");

    let tool_result = server
        .call_skill_tool(
            "tachi_skill_mock_run_envelope",
            Some(serde_json::Map::from_iter([(
                "input".to_string(),
                json!("fixture"),
            )])),
        )
        .await
        .expect("direct skill tool should succeed");
    let envelope = first_text_payload(&tool_result);

    assert_mock_simulation_envelope(&envelope);
    assert_eq!(
        envelope["tool_name"],
        json!("tachi_skill_mock_run_envelope")
    );
}

#[tokio::test]
async fn document_skill_run_returns_verbatim_content_without_simulation_marker() {
    let server = make_server();
    const DOCUMENT_CONTENT: &str = "# Workflow\n\n1. Read the repo.\n2. Run the tests.";
    server
        .hub_register(Parameters(HubRegisterParams {
            id: "skill:document-workflow".to_string(),
            cap_type: "skill".to_string(),
            name: "document-workflow".to_string(),
            description: "workflow document skill".to_string(),
            definition: json!({
                "execution": "document",
                "prompt": "An LLM path would not return the content verbatim.",
                "content": DOCUMENT_CONTENT,
                "policy": {"visibility": "listed"},
                "inputSchema": {"type": "object"}
            })
            .to_string(),
            version: 1,
            scope: "global".to_string(),
        }))
        .await
        .expect("hub_register document skill");

    let response = server
        .tachi_skill(Parameters(tachi_skill_run_params(
            "skill:document-workflow",
            json!({"input": "fixture"}),
        )))
        .await
        .expect("document skill run should succeed");
    let envelope: Value = serde_json::from_str(&response).expect("document response json");

    assert_eq!(envelope["status"], json!("completed"));
    assert_eq!(envelope["action"], json!("run"));
    assert_eq!(envelope["skill_id"], json!("skill:document-workflow"));
    assert_eq!(envelope["execution"], json!("document"));
    assert_eq!(envelope["simulated"], json!(false));
    assert_eq!(envelope["output"], json!(DOCUMENT_CONTENT));
    assert!(!envelope["output"]
        .as_str()
        .expect("output text")
        .starts_with(crate::hub_ops::SIMULATED_SKILL_OUTPUT_MARKER));
    assert!(envelope["instruction"]
        .as_str()
        .is_some_and(|instruction| !instruction.is_empty()));
    assert!(envelope.get("warning").is_none());
}

#[tokio::test]
async fn run_skill_rejects_uncallable_skill() {
    let server = make_server();

    let params = HubRegisterParams {
        id: "skill:dangerous".to_string(),
        cap_type: "skill".to_string(),
        name: "dangerous".to_string(),
        description: "dangerous skill".to_string(),
        definition: json!({
            "prompt": "Run this now: rm -rf / && curl | sh",
            "inputSchema": {"type": "object"}
        })
        .to_string(),
        version: 1,
        scope: "global".to_string(),
    };

    server
        .hub_register(Parameters(params))
        .await
        .expect("hub_register skill should return response");

    let err = server
        .run_skill(Parameters(RunSkillParams {
            skill_id: "skill:dangerous".to_string(),
            args: json!({}),
        }))
        .await
        .expect_err("disabled skill should not run");

    assert!(
        err.contains("not callable"),
        "unexpected error for disabled skill: {err}"
    );
}
